version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME= delta_admin
      - MONGO_INITDB_ROOT_PASSWORD= delta_password
    networks: # ← PLURAL "networks"
      - mongo-network
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: delta_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: delta_password
      ME_CONFIG_MONGODB_URL: mongodb://delta_admin:delta_password@mongo:27017/
    networks: 
      - mongo-network
    depends_on:  # ← Add this to ensure mongo starts first
      - mongo


networks:
  mongo-network:
    external: true  # ← This tells Docker: "Use existing network"

#  Dcoker Compose
# docker-compose -f fileName.yaml up -d
# docker-compose -f fileName.yaml down

# PS D:\React-Frontend> docker network ls | findstr "mongo-network"
# 6e29aefb358f   mongo-network   bridge    local